### ISSUE TITLE
Document the process on how to replace the certificates (Apple, Microsoft)

### ISSUE THREAD

**Issue by gauthierpetetin** [MetaMask/metamask-desktop#382]
Cf. Notion discussion here: https://www.notion.so/Desktop-App-437bc880d89d49a9a1d892ed6ee87280?d=7878bbe87ddd4263a32faf4d17eb0a03#799d057db1c9495db5b90b130293ee5f

Additional comment from N. Ellul :
One last thing, don’t forget to consider the bus factor if it’s going to be hosted on Joao’s account. Perhaps check if ConsenSys IT can set an email address up for your team with credentials shared in 1Password. That way if Joao is ever not around, the team can still take action on anything that needs to be done regarding the listing or certificates.

**Comment by cryptotavares** [comment]
Added to notion - [here](https://www.notion.so/CI-sign-6f124f816a9047e4bd0ae38b277d65e9)
