### ISSUE TITLE
Replace window.fetch by cross-fetch

### ISSUE THREAD

**Issue by gauthierpetetin** [MetaMask/metamask-desktop#506]
Change it to cross-fetch and check if it works.
Identify why we need it, and explain it to the extension team.

**Comment by cryptotavares** [comment]
No need to replace window.fetch on the extension.. we can just polyfill the window object on desktop.

**Comment by cryptotavares** [comment]
Closed by the PRs below:
* https://github.com/MetaMask/desktop-extension/pull/32
* https://github.com/MetaMask/metamask-desktop/pull/512
